### PR TITLE
Subset operations and filter chaining

### PR DESCRIPTION
**Pull request by timominous**

### CODE REVIEW

**Comment by tannernelson** [comment]
Since Fluent is intended to work with all types of DBs, from MySQL to Mongo, the `Filter` class should not have any knowledge about SQL or joins. This code would be more appropriate in the `SQL` class or in the `SQLite` driver.

**Comment by timominous** [comment]
I see. I agree with that. Will close this PR.

**Comment by timominous** [comment]
@tannernelson would it be more appropriate if it would be made through the `Driver` protocol so that all the subclasses could handle the differences?

**Comment by tannernelson** [comment]
I think each Driver could add extensions onto the Filter classes that supply operand information, etc.

**Pull request closed without merging**
